### ISSUE TITLE
Capstone: DVP: Netflix Data

### ISSUE THREAD

**Issue by cviddy17** [BarbaraSchwarz/dvp-u6-netflix-data#1]
## Rubric Score
 
### Criteria 1: Pandas and CSV
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Pandas code was written well, creating the proper visualizations for the task. Great job!
 
### Criteria 2: Implementation of visualizations in spec
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ The graphs were all implemented properly, and they were explained very well.
 
### Criteria 3: Color
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Color was present in all graphs and was written properly and effectively.
 
### Criteria 4: Style
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ The overall presentation looked great! The title slide and font choice were consistent.

### Criteria 4: Presentation and framing of visualization
* _Score Level:_ 4/4 Exceeds Expectations
* _Comment(s):_ Visualization explanations went above and beyond traditional analysis and was very thorough. Good job!
 
### Overall Score: 20/20
This presentation was fantastic! Your analysis was spot on and the overall look and style of your presentation were excellent!

**Comment by BarbaraSchwarz** [comment]
Thanks very much for reviewing, Chad, and enjoying the presentation.
